controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
default:
    path: /{slug}
    controller: App\Controller\DefaultController::index
    requirements:
        slug: ".+"